// Application-wide constants

export const USER_ROLES = {
  ADMIN: "ADMIN",
  SUPERVISOR: "SUPERVISOR",
  WORKER: "WORKER",
};

export const SHIPMENT_TYPES = {
  INBOUND: "INBOUND",
  OUTBOUND: "OUTBOUND",
};

export const SHIPMENT_STATUS = {
  CREATED: "CREATED",
  ARRIVED: "ARRIVED",
  PUTAWAY: "PUTAWAY",
  PICKING: "PICKING",
  PACKED: "PACKED",
  SHIPPED: "SHIPPED",
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const TASK_TYPES = {
  PUTAWAY: "PUTAWAY",
  PICKING: "PICKING",
};

export const TASK_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
};

export const NOTIFICATION_TYPES = {
  ALERT: "ALERT",
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
};

export const PRIORITY_LEVELS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

export const PRODUCT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  LOW_STOCK: "LOW_STOCK",
};

export const VERIFICATION_RESULTS = {
  MATCH: "MATCH",
  MISMATCH: "MISMATCH",
  PENDING: "PENDING",
  LOW_CONFIDENCE: "LOW_CONFIDENCE",
};

export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 100,
};

export const OCCUPANCY_LEVELS = {
  LOW: 40,
  MEDIUM: 70,
  HIGH: 100,
};
